######
## theme.toml file for Rubenerd Rubi
## Hugo doesn't accept YAML for this file :<

name = "Rubenerd Rubi"
description = "The simplest theme I could make, featuring Rubi."
homepage = "https://rubenerd.com/"
min_version = "0.41"

[author]
  name = "Ruben Schade"
  homepage = "https://rubenerd.com/"

