######
## theme.toml file for Rubenerd Rubi
## Hugo doesn't accept YAML for this file :<

name = "Rubenerd Liner"
description = ""
homepage = "https://rubenerd.com/"
tags = [minimal, single-column]
features = [responsive]
min_version = "0.41"

[author]
  name = "Ruben Schade"
  homepage = "https://rubenerd.com/"

