---
baseurl: "https://rubenerd.com/"
title: "Rubénerd"
languageCode: "en-SG"
disableLiveReload: true
editor: "mvim"
metaDataFormat: "yaml"
paginate: 10
params:
  subtitle: "By Ruben Schade in s/Singapore/Sydney/ since 2004. Hi there!"
  html5shim: '<!--[if lt IE 9]><script src="/please-dont-use-ie.js"></script><![endif]-->'
  ISO8601: '2006-01-02T15:04:05-07:00'
  feedbackEmail: "weblog2017@rubenschade.com"
  buyCoffee: "http://ko-fi.com/A625HL"
  ownerTwitter: "@Rubenerd"
  ownerTwitterURL: "https://twitter.com/Rubenerd"
  siteTwitter: "@Rubenerd_blog"
  siteTwitterURL: "https://twitter.com/Rubenerd_blog"
permalinks:
  page: "/:filename/"
  post: "/:filename/"
  omake: "/omake/:filename"
log: false
stepAnalysis: false
author:
  name: "Ruben Schade"
taxonomies:
  category: "category"
  tag: "tag"
---
