---
baseURL: https://rubenerd.com/
disableKinds: [section]
disableLiveReload: true
editor: vim
languageCode: en-SG
theme: rubenerd-rubi
title: Rubenerd

params:

  author:
    first: Ruben
    last: Schade
    city: Sydney
    country: Australia
    twitter: rubenerd
    why: These map to schema.org data.

  description: By Ruben Schade in s/ Singapore/ Sydney/ since 2004-ish.
  licence_title: Creative Commons Attribution Share-Alike 3.0
  licence_url: https://creativecommons.org/licenses/by-sa/3.0/
  logo: logo.png
  logo_rss: rss.png
  twitter: rubenerd_blog

  podcast:
    category: show
    cover: http://showfeed.rubenerd.com/itunes-cover.png
    explicit: no
    feed: http://showfeed.rubenerd.com/
    itunes: https://itunes.apple.com/au/podcast/rubenerd-show/id1003680071
    itunes_category: Society & Culture
    itunes_sub: Personal Journals
    keywords: australia,sydney,singapore,thoughts,tech,anime,jazz,ruben schade,onsug,overnightscape underground
    overcast: https://overcast.fm/itunes1003680071/rubenerd-show
    pocket_casts: http://pca.st/ybXl
    publisher: me@rubenschade.com
    summary: Ruben's longrunning harmless podcast of observations from Singapore, Malaysia, and Australia.
    tagline: A harmless show of observations, since 2005
    title: Rubenerd Show

menu:
  header:
  - identifier: home
    name: Latest posts
    title: Home
    url: /
    weight: 1
    identifier: about
  - name: Author, dedication, and site information
    title: About
    url: /about/
    weight: 2
  - identifier: archives
    name: Lists of all posts by year, category, and writing location
    title: Archives
    url: /archives/
    weight: 3
  - identifier: podcast
    name: My harmless podcast of observations
    title: Podcast
    url: /show/
    weight: 4
  - identifier: omake
    name: Extra goodies
    title: Omake
    url: /omake-pages/
    weight: 5

permalinks:
  omake: /omake/:filename/
  page: /:filename/
  post: /:filename/

taxonomies:
  category: category
  tag: tag
  year: year

disableKinds:
- categories
- tags

