---
baseurl: "http://rubenerd.com/"
title: "Rubénerd"
languageCode: "en-SG"
disableLiveReload: true
editor: "mvim"
metaDataFormat: "yaml"
paginate: 10
params:
  subtitle: "By Ruben Schade in s/Singapore/Sydney/"
  html5shim: '<!--[if lt IE 9]><script src="/please-dont-use-ie.js"></script><![endif]-->'
permalinks:
  page: "/:filename/"
  post: "/:filename/"
log: false
stepAnalysis: true
author:
  name: "Ruben Schade"
taxonomies:
  category: "category"
  tags: "tags"
---
