---
baseurl: "http://rubenerd.com/"
title: "Rubénerd"
languageCode: "en-SG"
disableLiveReload: true
paginate: 10
params:
  subtitle: "By Ruben Schade in s/Singapore/Sydney/"
  html5shim: '<!--[if lt IE 9]><script src="/please-dont-use-ie.js"></script><![endif]-->'
  respect: "<!-- Where are the massive, dynamically loaded JS libraries and fonts?! You're welcome -->"
permalinks:
  page: "/:filename/"
  post: "/:filename/"
log: false
stepAnalysis: true
author:
  name: "Ruben Schade"
menu:
  categories:
    - Name: anime
      Description: "Angmoh posts about moeblob/scifi anime, manga and desu"
      Url: "/anime/"
    - Name: hardware
      Description: "Posts on Apple, phones, mechanical keyboards and such"
      Url: "/hardware/"
    - Name: internet
      Description: "Posts on browsers, web standards, security and privacy"
      Url: "/internet/"
    - Name: media
      Description: "Posts with photos, music and other things"
      Url: "/media/"
    - Name: show
      Description: "My 2005-2009 nerdy slice of life podcast"
      Url: "/show/"
    - Name: software
      Description: "Posts on Mac, *nix and virtualisation, where I work and spend my free time"
      Url: "/software/"
    - Name: thoughts
      Description: "Posts on multifarious ruminations"
      Url: "/thoughts/"
---
