---
baseURL:           "https://rubenerd.com"
canonifyURLs:      true
disableLiveReload: true
editor:            "vim"
languageCode:      "en-SG"
metaDataFormat:    "yaml"
paginate:          10
theme:             "rubenerd-nostalgia"
title:             "Rubenerd"

params:

  author:
    coffee:   "http://ko-fi.com/A625HL" 
    email:    "weblog2017@rubenschade.com"
    failbook: "ruben.schade"
    name:     "Ruben Schade"
    profile:  "/about/"
    twitter:  "Rubenerd"
    wishlist: "https://www.wishlistr.com/rubenerd"

  cite:
    dedication:     "my mum"
    dedication_url: "/dedication/"
    host:           "Joviam"
    host_url:       "https://joviam.com/"
    os:             "FreeBSD"
    os_url:         "https://www.freebsd.org/"
    software:       "Hugo"
    software_url:   "https://gohugo.io/"
    server:         "nginx"
    server_url:     "https://nginx.org/"
    
  info:
    copyright: "Original material © 2004–17"
    feed:      "/feed/"
    logo:      "logo.png"
    logo_rss:  "logo.rss.png"
    lyrics:    "Time for a meeting, in digital space;<br />Because for thousands of years, we couldn't agree on a place."
    tagline:   "By Ruben Schade in s/Singapore/Sydney/"
    twitter:   "Rubenerd_Blog"

  licence:
    title: "Creative Commons Attribution Share-Alike 3.0"
    url:   "https://creativecommons.org/licenses/by-sa/3.0/"

  navigation:
    - title: "Home"
      url:   "/"
      info:  "Latest posts!"
    - title: "About"
      url:   "/about/"
      info:  "Author and site information"
    - title: "Archives"
      url:   "/archives/"
      info:  "Lists of all posts, ordered by category"
    - title: "Buy coffee"
      url:   "http://ko-fi.com/A625HL"
      info:  "Show your support with a up of caffeinated beverage!"
    - title: "Omake…"
      url:   "/omake/"
      info:  "Extra goodies"

  categories:
    - title: "Anime"
      url:   "/anime/"
      info:  "Posts about anime, manga, weebness, and figs"
    - title: "Hardware"
      url:   "/hardware/"
      info:  "Posts on computers, servers, phones, jaffle irons"
    - title: "Internet"
      url:   "/internet/"
      info:  "Posts on websites, online privacy and security, standards"
    - title: "Museum"
      url:   "/museum/"
      info:  "Posts imported from retired or deleted services"
    - title: "Podcast"
      url:   "/show/"
      info:  "Rubénerd Show: My harmless podcast of observations"
    - title: "Software"
      url:   "/software/"
      info:  "Mostly posts on macOS, FreeBSD, (GNU/)Linux"
    - title: "Thoughts"
      url:   "/thoughts/"
      info:  "Posts on multifarious observations"


  podcast:
    category:        "show"
    cover:           "http://showfeed.rubenerd.com/itunes-cover.png"
    explicit:        "no"
    feed:            "http://showfeed.rubenerd.com/"
    itunes:          "https://itunes.apple.com/au/podcast/rubenerd-show/id1003680071"
    itunes_category: "Society & Culture"
    itunes_sub:      "Personal Journals"
    keywords:        "australia,sydney,singapore,thoughts,tech,anime,jazz,ruben schade,onsug,overnightscape underground"
    overcast:        "https://overcast.fm/itunes1003680071/rub-nerd-show"
    pocket_casts:    "http://pca.st/ybXl"
    publisher:       "me@rubenschade.com"
    summary:         "Ruben's longrunning harmless podcast of observations from Singapore, Malaysia, and Australia."
    tagline:         "A harmless show of observations, since 2005."
    title:           "Rubénerd Show"

permalinks:
  page:  "/:filename/"
  post:  "/:filename/"
  omake: "/omake/:filename/"

taxonomies:
  category: "category"

