---
- name: Build dependencies for rubenerd.com
  hosts: localhost
  become: yes
  
  vars:
    python: 37

  tasks:

  - name: Install FreeBSD packages
    pkgng:
      name: "{{ item.name }}"
      state: present
    loop:
      - ffmpeg
      - gohugo
      - ImageMagick7-nox11
      - jpegoptim
      - ncftp
      - pngcrush
      - "py{{ vars.python }}-eyed3"
      - "py{{ vars.python }}-internetarchive"
    when: ansible_distribution == "FreeBSD"

  - name: Build required ports
    portinstall: 
      name: audio/lame
      state: present
    when: ansible_distribution == "FreeBSD"

  - name: Install NetBSD/macOS packages from pkgsrc
    pkgin:
      name: "{{ item.name }}"
      state: present
    loop:
      - eyed3
      - ffmpeg4
      - hugo
      - ImageMagick
      - jpegoptim
      - lame
      - ncftp3
      - pngcrush
      - "py{{ vars.python }}-pip"
    when: ansible_distribution == "NetBSD" || ansible_distribution = "Darwin"

  - name: Install pips
    pip:
      name: "{{ item.name }}"
      state: present
    loop:
      - eyeD3
      - internetarchive
    when: ansible_distribution == "NetBSD" || ansible_distribution = "Darwin"

